const schedual = [
  {
    class: "Class 1",
    subject: "Mathamatics",
    date: "01 / 05 / 2025",
    time: "Start Time : 09:00 AM | End Time : 1:00 PM",
    feeMonth: "January",
    amount: "3000",
    name: "Ali",
    fatherName: "Junaid",
    notice: "Student must be on time and bring their water bottel!",
  },
  {
    class: "Class 1",
    subject: "English",
    date: "10 / 05 / 2025",
    time: "Start Time : 09:00 AM | End Time : 1:00 PM",
    feeMonth: "January",
    amount: "3000",
    name: "Asfer",
    fatherName: "Jawwad",
    notice: "Student must be on time and bring their water bottel!",
  },
  {
    class: "Class 2",
    subject: "Urdu",
    date: "01 / 05 / 2025",
    time: "Start Time : 09:00 AM | End Time : 1:00 PM",
    feeMonth: "January",
    amount: "3000",
    name: "Zafer",
    fatherName: "Akram",
    notice: "Student must be on time and bring their water bottel!",
  },
  {
    class: "Class 2",
    subject: "English",
    date: "11 / 05 / 2025",
    time: "Start Time : 09:00 AM | End Time : 1:00 PM",
    feeMonth: "January",
    amount: "3000",
    name: "Jhanzeeb",
    fatherName: "Farroq",
    notice: "Student must be on time and bring their water bottel!",
  },
  {
    class: "Class 3",
    subject: "Histroy",
    date: "15 / 05 / 2025",
    time: "Start Time : 09:00 AM | End Time : 1:00 PM",
    feeMonth: "January",
    amount: "3000",
    name: "Usman",
    fatherName: "Adeel",
    notice: "Student must be on time and bring their water bottel!",
  },
  {
    class: "Class 3",
    subject: "Math",
    date: "01 / 05 / 2025",
    time: "Start Time : 09:00 AM | End Time : 1:00 PM",
    feeMonth: "January",
    amount: "3000",
    name: "Salar",
    fatherName: "Fahad",
    notice: "Student must be on time and bring their water bottel!",
  },
  {
    class: "Class 4",
    subject: "Sience",
    date: "20 / 05 / 2025",
    time: "Start Time : 09:00 AM | End Time : 1:00 PM",
    feeMonth: "January",
    amount: "3000",
    name: "Ali",
    fatherName: "Junaid",
    notice: "Student must be on time and bring their water bottel!",
  },
  {
    class: "Class 4",
    subject: "English",
    date: "23 / 05 / 2025",
    time: "Start Time : 09:00 AM | End Time : 1:00 PM",
    feeMonth: "January",
    amount: "3000",
    name: "Ali",
    fatherName: "Junaid",
    notice: "Student must be on time and bring their water bottel!",
  },
  {
    class: "Class 4",
    subject: "Sience",
    date: "20 / 05 / 2025",
    time: "Start Time : 09:00 AM | End Time : 1:00 PM",
    feeMonth: "January",
    amount: "3000",
    name: "Ali",
    fatherName: "Junaid",
    notice: "Student must be on time and bring their water bottel!",
  },
  {
    class: "Class 5",
    subject: "Physics",
    date: "01 / 05 / 2025",
    time: "Start Time : 09:00 AM | End Time : 1:00 PM",
    feeMonth: "January",
    amount: "3000",
    name: "Mohsin",
    fatherName: "Junaid",
    notice: "Student must be on time and bring their water bottel!",
  },
  {
    class: "Class 5",
    subject: "Physics",
    date: "01 / 05 / 2025",
    time: "Start Time : 09:00 AM | End Time : 1:00 PM",
    feeMonth: "January",
    amount: "3000",
    name: "Mohsin",
    fatherName: "Junaid",
    notice: "Student must be on time and bring their water bottel!",
  },
  {
    class: "Class 5",
    subject: "Chemistry",
    date: "01 / 05 / 2025",
    time: "Start Time : 09:00 AM | End Time : 1:00 PM",
    feeMonth: "January",
    amount: "3000",
    name: "Fayaaz",
    fatherName: "Ali",
    notice: "Student must be on time and bring their water bottel!",
  },
];

const examData = [
  {
    name: "Ali",
    fatherName: "Junaid",
    percentage: "88.2",
    group: "A",
    class: "Class 1",
  },
  {
    name: "Usman",
    fatherName: "Faraz",
    percentage: "70.3",
    group: "B",
    class: "Class 3",
  },
  {
    name: "Akram",
    fatherName: "Junaid",
    percentage: "91",
    group: "A",
    class: "Class 2",
  },
  {
    name: "Muhammad",
    fatherName: "Gulzaar",
    percentage: "93.5",
    group: "A",
    class: "Class 2",
  },
  {
    name: "Fasseh",
    fatherName: "Asad",
    percentage: "87.4",
    group: "B",
    class: "Class 3",
  },
  {
    name: "Fahad",
    fatherName: "Usman",
    percentage: "94",
    group: "A",
    class: "Class 3",
  },
  {
    name: "Jhanzeeb",
    fatherName: "Junaid",
    percentage: "95.5",
    group: "B",
    class: "Class 4",
  },
  {
    name: "Ali",
    fatherName: "Junaid",
    percentage: "88.2",
    group: "A",
    class: "Class 1",
  },
  {
    name: "Usman",
    fatherName: "Faraz",
    percentage: "70.3",
    group: "B",
    class: "Class 3",
  },
  {
    name: "Mohsin",
    fatherName: "Jareer",
    percentage: "97.9",
    group: "A",
    class: "Class 4",
  },
  {
    name: "Junaid",
    fatherName: "Jawwad",
    percentage: "99.3",
    group: "B",
    class: "Class 5",
  },
  {
    name: "Ali",
    fatherName: "Junaid",
    percentage: "93.7",
    group: "A",
    class: "Class 5",
  },
  {
    name: "Fasseh",
    fatherName: "Asad",
    percentage: "87.4",
    group: "B",
    class: "Class 3",
  },
  {
    name: "Fahad",
    fatherName: "Usman",
    percentage: "94",
    group: "A",
    class: "Class 3",
  },
];

const feesData = [
  {
    monthly: "2,000",
    yearly: "2,00,000",

    group: "A",
    class: "Class 1",
  },
  {
    monthly: "3,000",
    yearly: "3,00,000",

    group: "B",
    class: "Class 3",
  },
  {
    monthly: "2,000",
    yearly: "2,00,000",

    group: "A",
    class: "Class 2",
  },
  {
    monthly: "2,000",
    yearly: "2,00,000",

    group: "A",
    class: "Class 2",
  },
  {
    monthly: "3,000",
    yearly: "3,00,000",

    group: "B",
    class: "Class 3",
  },
  {
    monthly: "3,000",
    yearly: "3,00,000",

    group: "A",
    class: "Class 3",
  },
  {
    monthly: "4,000",
    yearly: "4,00,000",

    group: "B",
    class: "Class 4",
  },
  {
    monthly: "2,000",
    yearly: "2,00,000",

    group: "A",
    class: "Class 1",
  },
  {
    monthly: "3,000",
    yearly: "3,00,000",

    group: "B",
    class: "Class 3",
  },
  {
    monthly: "4,000",
    yearly: "4,00,000",

    group: "A",
    class: "Class 4",
  },
  {
    monthly: "5,000",
    yearly: "5,00,000",

    group: "B",
    class: "Class 5",
  },
  {
    monthly: "5,000",
    yearly: "5,00,000",

    group: "A",
    class: "Class 5",
  },
  {
    monthly: "2,000",
    yearly: "2,00,000",

    group: "B",
    class: "Class 3",
  },
  {
    monthly: "2,000",
    yearly: "2,00,000",

    group: "A",
    class: "Class 3",
  },
  {
    monthly: "2,000",
    yearly: "2,00,000",

    group: "A",
    class: "Class 3",
  },
];

export default { schedual, examData, feesData };
